import jsPDF from "jspdf"
import domtoimage from "dom-to-image"
import type { MachineData } from "@/types/report";

interface ExportOptions {
  title?: string
  interval?: string
  machineId?: string
  dataType?: string
}

export const exportChartMachinePDF = async (
  data: MachineData[],
  chartElement: HTMLElement | null,
  options: ExportOptions = {}
) => {
  if (!chartElement) return

  const dataUrl = await domtoimage.toPng(chartElement)

  const pdf = new jsPDF("p", "mm", "a4")

  await addHeader(pdf)

  let yPosition = 55

  pdf.setFontSize(18)
  pdf.setFont("helvetica", "bold")
  pdf.text(options.title || "Report", 14, yPosition)
  yPosition += 8

  pdf.setFontSize(12)
  pdf.setFont("helvetica", "normal")
  pdf.text(`Interval: ${options.interval}`, 14, yPosition)
  yPosition += 6
  pdf.text(`Data Type: ${options.dataType || "Summary"}`, 14, yPosition)

  if (options.machineId) {
    yPosition += 6
    pdf.text(`Machine ID: ${options.machineId}`, 14, yPosition)
  }

  yPosition += 10

  pdf.addImage(dataUrl, "PNG", 14, yPosition, 182, 100)
  yPosition += 115

  pdf.setFont("helvetica", "bold")
  pdf.text("Analytic Report Summary", 14, yPosition)
  yPosition += 6

  const PAGE_TOP = 55
  const PAGE_BOTTOM = 280

  const renderTableHeader = (pdf: jsPDF, y: number) => {
    pdf.setFontSize(10)
    pdf.setFont("helvetica", "normal")

    const colX = [14, 45, 65, 85, 115, 140, 165]

    pdf.text("Date", colX[0], y)
    pdf.text("OKCount", colX[1], y)
    pdf.text("NGCount", colX[2], y)
    pdf.text("OKCountYear", colX[3], y)
    pdf.text("NGCountYear", colX[4], y)
    pdf.text("NGRate (%)", colX[5], y)
    pdf.text("NGYearRate (%)", colX[6], y)

    y += 4
    pdf.line(14, y, 196, y)

    return y + 6
  }

  pdf.setFontSize(10)
  pdf.setFont("helvetica", "normal")

  const colX = [14, 45, 65, 85, 115, 140, 165]

  yPosition = renderTableHeader(pdf, yPosition)

  for (const d of data) {
    if (yPosition > PAGE_BOTTOM) {
      pdf.addPage()
      await addHeader(pdf)
      yPosition = PAGE_TOP

      yPosition = renderTableHeader(pdf, yPosition)
    }

    pdf.text(d.date, colX[0], yPosition)
    pdf.text(d.OKCount.toString(), colX[1], yPosition)
    pdf.text(d.NGCount.toString(), colX[2], yPosition)
    pdf.text(d.OKCountYear.toString(), colX[3], yPosition)
    pdf.text(d.NGCountYear.toString(), colX[4], yPosition)
    pdf.text(`${d.NGRate.toFixed(1)}%`, colX[5], yPosition)
    pdf.text(`${d.NGYearRate.toFixed(1)}%`, colX[6], yPosition)

    yPosition += 6
  }

  pdf.setFontSize(9)
  pdf.text("Generated by Dashboard Monitoring System", 14, 290)

  pdf.save(`${options.title || "Report"}.pdf`)
}

const getBase64Image = (url: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.crossOrigin = "Anonymous"

    img.onload = () => {
      const canvas = document.createElement("canvas")
      canvas.width = img.width
      canvas.height = img.height
      const ctx = canvas.getContext("2d")

      if (ctx) {
        ctx.drawImage(img, 0, 0)
        resolve(canvas.toDataURL("image/png"))
      } else {
        reject(new Error("Failed to get canvas context"))
      }
    }

    img.onerror = reject
    img.src = url
  })
}

const addHeader = async (pdf: jsPDF) => {
  try {
    const logoBase64 = await getBase64Image("/logo-pdf.png")

    pdf.addImage(logoBase64, "PNG", 14, 3, 40, 40)

    pdf.setFontSize(18)
    pdf.setFont("helvetica", "bold")
    pdf.text("Report Documentation", 120, 18, { align: "center" })

    pdf.setFontSize(14)
    pdf.setFont("helvetica", "normal")
    pdf.text(
      "Monitoring System REC Technology Corporation",
      120,
      25,
      { align: "center" }
    )

    pdf.setFontSize(10)
    pdf.text(
      "4F, No. 28, Sec 2, Nankan Rd, Luzhu Dist, Taoyuan City, 33855, Taiwan",
      120,
      31,
      { align: "center" }
    )

    pdf.setLineWidth(0.5)
    pdf.line(14, 38, 196, 38)
  } catch {
    pdf.setFontSize(18)
    pdf.setFont("helvetica", "bold")
    pdf.text("Report Documentation", 120, 18, { align: "center" })
    pdf.line(14, 38, 196, 38)
  }
}
