import jsPDF from "jspdf";
import domtoimage from "dom-to-image";
import type { MachineDataAnalytic } from "@/types/report";

interface ExportOptions {
  title?: string;
  dateRange?: { from?: Date; to?: Date };
  dataType?: string;
}

export const exportChartPDF = async (
  data: MachineDataAnalytic[],
  chartElement: HTMLElement | null,
  options: ExportOptions = {}
) => {
  if (!chartElement) return;

  const dataUrl = await domtoimage.toPng(chartElement);

  const pdf = new jsPDF("p", "mm", "a4");

  await addHeader(pdf);

  let yPosition = 55;

  pdf.setFontSize(18);
  pdf.setFont("helvetica", "bold");
  pdf.text(options.title || "Report", 14, yPosition);
  yPosition += 8;

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  pdf.text(`Date: ${formatFullDateTime(options.dateRange?.to)}`, 14, yPosition);
  yPosition += 6;
  pdf.text(`Data Type: ${options.dataType || "Summary"}`, 14, yPosition);
  yPosition += 10;

  pdf.addImage(dataUrl, "PNG", 14, yPosition, 182, 100);
  yPosition += 115;

  pdf.setFont("helvetica", "bold");
  pdf.text("Analytic Report Summary", 14, yPosition);
  yPosition += 6;
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  const colX = [14, 50, 70, 90, 110, 140];
  pdf.text("Machine", colX[0], yPosition);
  pdf.text("OK", colX[1], yPosition);
  pdf.text("NG", colX[2], yPosition);
  pdf.text("Retry", colX[3], yPosition);
  pdf.text("Daily Retry (%)", colX[4], yPosition);
  pdf.text("Yearly Retry (%)", colX[5], yPosition);
  yPosition += 4;
  pdf.line(14, yPosition, 196, yPosition);
  yPosition += 6;

  data.forEach((d) => {
    pdf.text(d.machine, colX[0], yPosition);
    pdf.text(d.ok.toString(), colX[1], yPosition);
    pdf.text(d.ng.toString(), colX[2], yPosition);
    pdf.text(d.retry.toString(), colX[3], yPosition);
    pdf.text(`${d.rateRetry.toFixed(1)}%`, colX[4], yPosition);
    pdf.text(`${d.rateRetryYear.toFixed(1)}%`, colX[5], yPosition);
    yPosition += 6;
  });

  pdf.setFontSize(9);
  pdf.text("Generated by Dashboard Monitoring System", 14, 290);

  pdf.save(`${options.title || "Report"}.pdf`);
};

const getBase64Image = (url: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "Anonymous";
    
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      
      if (ctx) {
        ctx.drawImage(img, 0, 0);
        const dataURL = canvas.toDataURL("image/png");
        resolve(dataURL);
      } else {
        reject(new Error("Failed to get canvas context"));
      }
    };
    
    img.onerror = (error) => reject(error);
    img.src = url;
  });
};

const addHeader = async (pdf: jsPDF) => {
  try {
    const logoBase64 = await getBase64Image("/logo-pdf.png");
    
    pdf.addImage(logoBase64, "PNG", 14, 3, 40, 40);
    
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.text("Report Documentation", 120, 18, { align: "center" });
    
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Monitoring System REC Technology Corporation`, 120, 25, { align: "center" });
    
    pdf.setFontSize(10);
    pdf.text("4F, No. 28, Sec 2, Nankan Rd, Luzhu Dist, Taoyuan City, 33855, Taiwan", 120, 31, { align: "center" });
    
    pdf.setLineWidth(0.5);
    pdf.line(14, 38, 196, 38);
    
  } catch (error) {
    console.error("Error loading logo:", error);
    
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.text("Report Documentation", 120, 18, { align: "center" });
    
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "normal");
    pdf.text("Monitoring System REC Technology Corporation", 120, 25, { align: "center" });
    
    pdf.setFontSize(10);
    pdf.text("4F, No. 28, Sec 2, Nankan Rd, Luzhu Dist, Taoyuan City, 33855, Taiwan", 120, 31, { align: "center" });
    
    pdf.setLineWidth(0.5);
    pdf.line(14, 38, 196, 38);
  }
};

const formatFullDateTime = (date?: Date) => {
  if (!date) return "-";

  const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  const months = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
  ];

  const dayName = days[date.getDay()];
  const monthName = months[date.getMonth()];
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const dateNum = String(date.getDate()).padStart(2, "0");

  const hours = String(date.getHours()).padStart(2, "0");
  const minutes = String(date.getMinutes()).padStart(2, "0");
  const seconds = String(date.getSeconds()).padStart(2, "0");

  return `${dayName}, ${monthName} ${year}/${month}/${dateNum} ${hours}:${minutes}:${seconds}`;
};
